force-app/main/default/objects/Attendance__c/Attendance__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <description>This object represents data from the sign-in sheet to a class. One record per attendee.</description>
    <label>Attendance</label>
    <nameField>
        <displayFormat>att-{000000000}</displayFormat>
        <label>AttendanceId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance__c/fields/Class__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance__c/fields/Participant__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Participant</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Participant__c.OwnerId</field>
            <operation>equals</operation>
            <valueField>$Source.OwnerId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Participant__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance_Queue_Item__c/Attendance_Queue_Item__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <label>Attendance_Queue_Item</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Attendance_Queue_Item_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance_Queue_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendance_Queue_Item__c/fields/Class__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Attendance_Queue_Items</relationshipLabel>
    <relationshipName>Attendance_Queue_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attendance_Queue_Item__c/fields/message__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>message__c</fullName>
    <label>message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Attendance_Queue_Item__c/fields/Name__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendance_Queue_Item__c/fields/Participant_Email__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Participant_Email__c</fullName>
    <label>Participant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendance_Queue_Item__c/fields/phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>phone__c</fullName>
    <label>phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <description>This object represents a class, such as Yoga, Zumba, etc.</description>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>電郵
Correo electrónico</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Phone__c</fullName>
    <inlineHelpText>電話
Teléfono</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AttendeeController.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or
 * https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class AttendeeController {
    
    @AuraEnabled
    public static String login(String firstName, String lastName, String phoneNumber, String email, String clazz){
        // Create custom object containing Strings only. 
        Attendance_Queue_Item__c attdc = new Attendance_Queue_Item__c();
        attdc.Class__c = clazz;
        if (lastName != null){
            attdc.Name__c = firstName+' '+lastName;
        } else {
            attdc.Name__c = firstName;
        }
        attdc.phone__c = phoneNumber;
        attdc.Participant_Email__c = email;
        //attdc.message_uuid__c = genUuid();
        //attdc.message_string__c = genUuid();
        
        //Message__c message = new Message__c();
        //message.UUID__c = uuid;
        //insert message;
        
        insert attdc;
        
        // After UI displays message, it would trigger a delete of the attendance queue item
        // We'll probably want to have a clean up every now and then.
        return attdc.Id;
        
        /*int max_wait_secs = 60 // Only wait 1 minute
        for (int t = 0; t < max_wait_secs; t++) {
            if (attdc.message_type__c == "error") 
                String error = attdc.message__c;
            else
            	String message = attdc.message__c;
            Thread.sleep(1000);
        }*/
 		// After insert, the Apex trigger will fire and look up the participant.         
		// TODO: At this point if anything go wrong, we need to wait a little and 
		// look up an error-custom-object created by the tigger and fire the error 
		// message back to the user. 
        
        // TODO: This needs to be moved to queue reader class once above works
        /*List<Participant__c> participants = 
            [SELECT OwnerId, Email__c FROM Participant__c WHERE Email__c = :email ];
        System.debug(participants.size());
        if(participants.size() == 1){
        	Attendance__c attendance = new Attendance__c();
            attendance.Class__c = clazz;
            attendance.Participant__c = participants.get(0).Id;
            insert attendance;
        } else {
            //do nothing
        }*/
        
    }
    
    @AuraEnabled
    public static String[] getMessage(String id) {
        Attendance_Queue_Item__c attendance_item =
                [SELECT message_type__c, message__c FROM Attendance_Queue_Item__c WHERE Id = :id];
        return new String[] { attendance_item.message_type__c, attendance_item.message__c };
    }
    
    @AuraEnabled
    public static List<Class__c> getClasses(){
        List<Class__c> classes = [SELECT Id, Name FROM Class__c ORDER BY Name];
        return classes;
    }
}