force-app/main/default/objects/Participant__c/Participant__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <label>Participant</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Participant__c/fields/City__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>City__c</fullName>
    <inlineHelpText>城市
Ciudad</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Date_Of_Birth__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Date_Of_Birth__c</fullName>
    <inlineHelpText>出生日期
Fecha de nacimiento</inlineHelpText>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Email__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>電郵
Correo electrónico</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Emergency_Contact_Name__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Emergency_Contact_Name__c</fullName>
    <inlineHelpText>緊急聯繫人姓名
Nombre del contacto de emergencia</inlineHelpText>
    <label>Emergency Contact Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Emergency_Contact_Phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <inlineHelpText>電話號碼
Número de teléfono</inlineHelpText>
    <label>Emergency Contact Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Gender__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Gender__c</fullName>
    <inlineHelpText>性別
Sexo</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prefer not to say</fullName>
                <default>true</default>
                <label>Prefer not to say</label>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Phone__c</fullName>
    <inlineHelpText>電話
Teléfono</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Race__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Race__c</fullName>
    <inlineHelpText>種族/族裔
Raza/ Etnia</inlineHelpText>
    <label>Race/Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prefer not to say</fullName>
                <default>true</default>
                <label>Prefer not to say</label>
            </value>
            <value>
                <fullName>African American/African</fullName>
            </value>
            <value>
                <fullName>Asian/Pacific Islander</fullName>
            </value>
            <value>
                <fullName>Caucasian</fullName>
            </value>
            <value>
                <fullName>Latino/Chicano</fullName>
            </value>
            <value>
                <fullName>Native American</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Participant__c/fields/State__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>State__c</fullName>
    <inlineHelpText>州
Estado</inlineHelpText>
    <label>State</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Participant__c/fields/Zipcode__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Zipcode__c</fullName>
    <inlineHelpText>郵政編碼
Código postal</inlineHelpText>
    <label>Zipcode</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/Registration_Queue_Item__c.object-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomObject>
    <label>Registration_Queue_Item</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registration_Queue_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Queue_Item__c/fields/AnyHealthCondition__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>AnyHealthCondition__c</fullName>
    <label>AnyHealthCondition</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/City__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Date_of_birth__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Email__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Emergency_contact_name__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Emergency_contact_name__c</fullName>
    <label>Emergency contact name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Emergency_contact_phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Emergency_contact_phone__c</fullName>
    <label>Emergency contact phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/ExerciseLevel__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>ExerciseLevel__c</fullName>
    <label>ExerciseLevel</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/ExistingHealthCondition__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>ExistingHealthCondition__c</fullName>
    <label>ExistingHealthCondition</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Gender__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/ParticipantPosition__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>ParticipantPosition__c</fullName>
    <label>ParticipantPosition</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Phone__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Race__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/ReferralSource__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>ReferralSource__c</fullName>
    <label>ReferralSource</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/State__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Street_Address__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Queue_Item__c/fields/Zipcode__c.field-meta.xml
<!--
  ~ Copyright (c) 2018, salesforce.com, inc.
  ~ All rights reserved.
  ~ Licensed under the BSD 3-Clause license.
  ~ For full license text, see LICENSE.txt file in the repo root or
  ~ https://opensource.org/licenses/BSD-3-Clause
  -->

<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateParticipantController.cls
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the repo root or
 * https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class CreateParticipantController {
    
    @AuraEnabled
    public static String create(String fullName, String phoneNumber, String email, 
                                String dateOfBirth, String streetAddr, String city, 
                                String state, String zipcode, String emergencyContactFullName, 
                                String emergencyContactPhoneNumber, String gender, String race, 
                                String existingHealthCondition, String anyHealthCondition, 
                                String referralSource, String exerciseLevels,
                                String participantPositions, String preferredLanguages, 
                                String enjoyableActivities, String healthImprove) {
        // Create custom object containing Strings only. 
        Registration_Queue_Item__c participant = new Registration_Queue_Item__c();
                                    
        participant.Name = fullName;
        participant.Phone__c = phoneNumber;
        participant.Email__c = email;

        if (dateOfBirth == null) {
        	participant.Date_of_birth__c = null;                                
        } else {
        	System.debug('Parsing date: ' + dateOfBirth);
            String[] yearMonthDay = dateOfBirth.split('-');
            participant.Date_of_birth__c = date.newinstance(Integer.valueOf(yearMonthDay[0]), Integer.valueOf(yearMonthDay[1]), Integer.valueOf(yearMonthDay[2]));
        }                           
                                    
        participant.Street_Address__c = streetAddr;
        participant.City__c = city;
        participant.State__c = state;
        if (zipCode == null) {
        	participant.Zipcode__c = null;	                                
        } else {
            try {
            	participant.Zipcode__c = Integer.valueOf(zipcode);
            } catch (Exception e) {
                participant.Zipcode__c = null;
            }
        }
        participant.Emergency_contact_name__c = emergencyContactFullName;
        participant.Emergency_contact_phone__c = emergencyContactPhoneNumber;
                                    
        participant.Gender__c = gender;
        participant.Race__c = race;
        
        participant.ExistingHealthCondition__c = existingHealthCondition;
        participant.AnyHealthCondition__c = anyHealthCondition;
        participant.ReferralSource__c = referralSource;
        participant.ExerciseLevel__c = exerciseLevels;
        participant.ParticipantPosition__c = participantPositions;
        participant.PreferredLanguage__c = preferredLanguages;
        participant.EnjoyableActivity__c = enjoyableActivities;
        participant.Health_Condition_Improve__c = healthImprove;                            
                                    
        insert participant;                       
        
        // After UI displays message, it would trigger a delete of the attendance queue item
        // We'll probably want to have a clean up every now and then.
        return participant.Id;        
    }
    
    @AuraEnabled
    public static String[] getMessage(String id) {
        Registration_Queue_Item__c item =
                [SELECT message_type__c, message__c FROM Registration_Queue_Item__c WHERE Id = :id];
        return new String[] { item.message_type__c, item.message__c };
    }
    
    @AuraEnabled
    public static List<String> getGenderOptions() {
        Schema.DescribeFieldResult fieldResult = Participant__c.gender__c.getDescribe();
        System.debug('Retrieving genders: ' + fieldResult);
                List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> genderLabels = new List<String>();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding gender value: ' + value);
            genderLabels.add(value.getLabel());
        }
        return genderLabels;
    }
    
    @AuraEnabled
    public static List<String> getRaceOptions() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Race__c.getDescribe();
        System.debug('Retrieving races: ' + fieldResult);
                List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> raceLabels = new List<String>();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding race value: ' + value);
            raceLabels.add(value.getLabel());
        }
        return raceLabels;
    }

    @AuraEnabled
    public static List<String> getExistingHealthConditions() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Existing_Health_Conditions__c.getDescribe();
        System.debug('Retrieving existing health conditions: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> existingHealthConditionLabels = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding existing health condition value: ' + value);
            existingHealthConditionLabels.add(value.getLabel());
        }
        return existingHealthConditionLabels;

    }

    @AuraEnabled
    public static List<String> getAnyHealthCondition() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Any_Health_Condition__c.getDescribe();
        System.debug('Retrieving any health conditions: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> anyHealthConditionLabels = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding any health condition value: ' + value);
            anyHealthConditionLabels.add(value.getLabel());
        }
        return anyHealthConditionLabels;

    }

    @AuraEnabled
    public static List<String> getReferralSources() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Referral_Source__c.getDescribe();
        System.debug('Retrieving referral sources: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> referralSources = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding referral sources value: ' + value);
            referralSources.add(value.getLabel());
        }
        return referralSources;
    }

    @AuraEnabled
    public static List<String> getExerciseLevels() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Exercise_Level__c.getDescribe();
        System.debug('Retrieving exercise levels: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> exerciseLevels = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding exercise levels value: ' + value);
            exerciseLevels.add(value.getLabel());
        }
        return exerciseLevels;
    }

    @AuraEnabled
    public static List<String> getParticipantPositions() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Participant_Position__c.getDescribe();
        System.debug('Retrieving participant positions: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> participantPositions = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding participant position value: ' + value);
            participantPositions.add(value.getLabel());
        }
        return participantPositions;
    }

    @AuraEnabled
    public static List<String> getPreferredLanguages() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Preferred_Language__c.getDescribe();
        System.debug('Retrieving preferred languages: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> preferredLanguages = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding preferred language value: ' + value);
            preferredLanguages.add(value.getLabel());
        }
        return preferredLanguages;
    }

    @AuraEnabled
    public static List<String> getEnjoyableActivities() {
        Schema.DescribeFieldResult fieldResult = Participant__c.Enjoyable_Activities__c.getDescribe();
        System.debug('Retrieving enjoyable activities: ' + fieldResult);
        List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
        List<String> enjoyableActivities = new List<String> ();
        for (Schema.PicklistEntry value : values) {
            System.debug('Adding enjoyable activities value: ' + value);
            enjoyableActivities.add(value.getLabel());
        }
        return enjoyableActivities;
    }

}